#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "X + X + O2 <=> OX + OX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=1, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt211
""",
)

entry(
    index = 1,
    label = "X + NH3 <=> NH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=1, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt211
""",
)

entry(
    index = 2,
    label = "OX + NH3X <=> OHX + NH2_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.56e+21,'cm^2/(mol*s)'), n=0, Ea=(55964.2,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt211
""",
)

entry(
    index = 3,
    label = "OX + NH2_X <=> OHX + NH_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.78e+21,'cm^2/(mol*s)'), n=0, Ea=(139910,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt211
""",
)

entry(
    index = 4,
    label = "OX + NH_X <=> NX + OHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.29e+21,'cm^2/(mol*s)'), n=0, Ea=(45350.3,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt211
""",
)

entry(
    index = 5,
    label = "OHX + NH3X <=> H2O_X + NH2_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.11e+21,'cm^2/(mol*s)'), n=0, Ea=(80086.7,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt211
""",
)

entry(
    index = 6,
    label = "OHX + NH2_X <=> NH_X + H2O_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.48e+21,'cm^2/(mol*s)'), n=0, Ea=(76227.1,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt211
""",
)

entry(
    index = 7,
    label = "OHX + NH_X <=> NX + H2O_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.01e+21,'cm^2/(mol*s)'), n=0, Ea=(81051.6,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt211
""",
)

entry(
    index = 8,
    label = "OHX + OHX <=> OX + H2O_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.59e+21,'cm^2/(mol*s)'), n=0, Ea=(81051.6,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt211
""",
)

entry(
    index = 9,
    label = "X + H2O <=> H2O_X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=1, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt211
""",
)

entry(
    index = 10,
    label = "NX + NX <=> X + X + N2",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.01e+21,'cm^2/(mol*s)'), n=0, Ea=(113858,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt211
""",
)

entry(
    index = 11,
    label = "OX + NX <=> X + NOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.44e+21,'cm^2/(mol*s)'), n=0, Ea=(140875,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt211
""",
)

entry(
    index = 12,
    label = "NOX <=> X + NO",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.3e+17,'1/s'), n=0, Ea=(224822,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt211
""",
)

entry(
    index = 13,
    label = "NX + NOX <=> X + N2O_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.32e+21,'cm^2/(mol*s)'), n=0, Ea=(156314,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt211
""",
)

entry(
    index = 14,
    label = "N2O_X <=> X + N2O",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.5e+17,'1/s'), n=0, Ea=(9649,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt211
""",
)

entry(
    index = 15,
    label = "X + NH3X <=> H_X + NH2_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(5.83e+20,'cm^2/(mol*s)'), n=0, Ea=(110964,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt211
""",
)

entry(
    index = 16,
    label = "X + NH2_X <=> H_X + NH_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.29e+21,'cm^2/(mol*s)'), n=0, Ea=(155349,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt211
""",
)

entry(
    index = 17,
    label = "X + NH_X <=> NX + H_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.61e+21,'cm^2/(mol*s)'), n=0, Ea=(125437,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt211
""",
)

entry(
    index = 18,
    label = "OX + H_X <=> X + OHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.8e+21,'cm^2/(mol*s)'), n=0, Ea=(48245,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt211
""",
)

entry(
    index = 19,
    label = "H_X + OHX <=> X + H2O_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.8e+21,'cm^2/(mol*s)'), n=0, Ea=(92630.4,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt211
""",
)

entry(
    index = 20,
    label = "NH_X + NH3X <=> NH2_X + NH2_X",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(4.94901e+15,'m^2/(mol*s)'), n=0.652756, Ea=(120.135,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [N-R;*=NH]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [N-R;*=NH]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 21,
    label = "NX + NH3X <=> NH_X + NH2_X",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(4.94901e+15,'m^2/(mol*s)'), n=0.652756, Ea=(120.135,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [N-R;*#N]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [N-R;*#N]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 22,
    label = "X + X + NH3 <=> H_X + NH2_X",
    degeneracy = 1.5,
    kinetics = StickingCoefficient(A=0.024, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [N;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 1.5
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [N;VacantSite1;VacantSite2]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 1.5
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 23,
    label = "NX + NH2_X <=> NH_X + NH_X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(8.35926e+17,'m^2/(mol*s)'), n=-0.0183333, Ea=(30.05,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Abstracting;*R-H] for rate rule [:N#*;*-N-H]
    Euclidian distance = 3.605551275463989
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [Abstracting;*R-H] for rate rule [:N#*;*-N-H]
Euclidian distance = 3.605551275463989
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 24,
    label = "X + X + H2O <=> H_X + OHX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.032, n=0, Ea=(32.8627,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [H2O;VacantSite1;VacantSite2]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative
    Ea raised from 0.0 to 32.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [H2O;VacantSite1;VacantSite2]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
Ea raised from 0.0 to 32.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 25,
    label = "X + N2 <=> N#N.[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 5 used for Adsorbate;VacantSite
    Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
From training reaction 5 used for Adsorbate;VacantSite
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

